---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA84DYJ/V8JOAgiqCsO/s9uqqGQphf3JXiEf6WGpM+yggvyleI0vlHyW9XK3ciDbUxiOIUH9IrXcac46PtaxjIk3/ZD+pUN/pL1P8zKimLklXDd0IXC8/Tw8fRNiKbjR8zzCqnLyVHwuQ8HAg6skO2O2ug8J9ZmOTNrhdYfrtu7ZG+R7llEhpS2+6bS9z11L/T2KJgEcftqKa86piSBVvKrprrQrJBxOrl/gv/IijV3SHysgo75KzT8MyFNwDwrLrbR6MU0wRkNnqofg478D/kx8pOnC71msjwluNsRcGSAfaH9PMNIT/Fk67QMuWKj3G5cpMEQ3ANHyKOnSoHA18Nk9/UsMLOqAHFpUF9lVlDUQpbzsjzrXqnlsTVeoWrNJ6rP2VvnFW51iGgezpCIOk+8Tqq+nI4meuBXi2u7UPG2Uqc8nRWq+qFbl2/CIg8nS5tSSnS6k9lkhOIJDRsJxsiWRxb5IdyJMdHuuLZSYWhmFjRVRh/+ZjQ84krasHxxcK+j7JqmnwgSN+EBYgpVGOqmUU7jdbF9eFh8RZzB18lvPNBIuocZtn0rqH4ntXMwjOrmZnrdVK8f8PEiEhpm3dMmKjmLk0UWvrGY6VfI6STPNaA/yxPPPQnoCi4NQMIeh8L/1NkJ5MAe45RJF2OY+J7FFRsaVCPs3ZiftarlMlFANIwquB8LsqBz5OU1RhSlJFs4jeIPcdacgJlNQooblW4gYNtjitUG9NzTKg1TAr5yBHBAfJBDvbb/ZCmlRE6o7r7IhVZiYGAZSYTCWdKYn4z831uciKD4o9PVoXHS0g4EYSR51fwSUCvJm7c+cCeP4fgK9HjqOsNKl8rf5mOhYj/ufNifqNA9zo7+NozIkm+8pKj3CGKWOU1Fyfd7fLL7jcr5E/E/HRzYVja2DbtKpM3DnysPmWjEefMvUA1K+cGLgjdAabPwgMSmLA==
  template:
    metadata:
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
