---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-credentials
  namespace: default
spec:
  encryptedData:
    GITHUB_PAT: AgAI+kPh+x8lFKfiAgAHx22UYir6+97kQF7tGVt3s8HcVSSA07UIarPrnjvyt7ncTYN1NSm0HNzzLJKU7lblYxv5H0lRWWsGO2wRiGWofRz8ANMQgE6keu5QUTOu1kgenJBM9AJp+3YxtKi1GT0ERFUy1wOVQakJcTumBB2ZtZEZ1yX8e6sAxmtKmgu68qzXdQPP7O7Gj7UTWDM9VYPdizDjERh6yCuDMiAW/tj+1eZJHzpjGJKA2EgIE5SZD4glhrQpr2Fe9yv6gvYEeKN6joY8NVlVBvgf9vQzuriD2/aUmLK03qw6y1jhzFoSyefaFK1ZQHhe3EJFHLttGWx0SqEvLUPiXZIWTIZc0lv7wq3C9XC8nuD67no5zgLOUmxq65kSYyF5YJYt+QjxOkKCbfcZ3nEttZ7Eq3CD+E2gW4cRJhaRJc5T04pbGVpVgwQRahssjRZ7S/KDv/fCiyKCOvz6ngg+2xlcnnxTYgSi/lt1KXgnOFNtbebe6pCT4BwoZ7HwYmtN0vmGLt8KiP8hT52sRegwYFv50xvmZ8sAoEQn5PnicDLa6n5Q25Q+I8lgZcXttediVUdfTcVWnKsI8aLMoO3wWdHt+jUX8pc9i/E9ppjwJNKL4Dq/dTwHjp9TluBYAW25TEctL8JYrEiehXeuhl5FlE43hoZ76ew/HbAMUSVKjGWl+4OlFJfzVBUW6BTMNpzdsOlMQBMkUYp4bIK7CC00+UndekraNXG5xg8GnullYkRWPW+g
  template:
    metadata:
      name: github-credentials
      namespace: default
    type: Opaque
