# NOTE: For production, consider using SealedSecrets
---
apiVersion: v1
kind: Secret
metadata:
  name: coder-db-credentials
  namespace: coder
type: Opaque
stringData:
  password: "27Vae+zNy4xsneWs0sx1aAxX7yjG0BZl"
  url: "postgres://coder:27Vae+zNy4xsneWs0sx1aAxX7yjG0BZl@coder-postgres.coder.svc.cluster.local:5432/coder?sslmode=disable"
