# NodePort service for external access to Coder
---
apiVersion: v1
kind: Service
metadata:
  name: coder-nodeport
  namespace: coder
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: coder
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30700
